config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: "customised_registrations" }
  root 'welcome#index'

  namespace :client do
    resources :bank_accounts, only: [:index, :new, :create, :show]
  end

  namespace :admin do
    resources :transactions, only: [:index, :new, :create, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bank_accounts, only: [:update]
  end

end

app/models/bank_account.rb
class BankAccount < ActiveRecord::Base


  validates :branch_code, presence: true, format: { with: /\A[0-9]{5}\z/ }
  validates :sort_code, presence: true, format: { with: /\A[0-9]{5}\z/ }
  validates :account_number, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9]{11}\z/ }
  validates :rib_key, presence: true, format: { with: /\A[0-9]{2}\z/ }

  belongs_to :account_state, foreign_key: "account_state_id"
  belongs_to :user
  has_many :transactions, :dependent => :destroy

  after_create :setup_default_account_state

  def is_active?
    account_state_id == AccountState::ACTIVE_STATE_TID
  end

  def is_activation_pending?
    account_state_id == AccountState::PENDING_ACTIVATION_STATE_TID
  end

  def is_closed?
    account_state_id == AccountState::CLOSED_STATE_TID
  end

  private

    def setup_default_account_state
      self.update_attributes(account_state_id: AccountState::PENDING_ACTIVATION_STATE_TID)
    end


end

app/controllers/admin/bank_accounts_controller.rb
class Admin::BankAccountsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_bank_account
  before_action :require_to_be_admin


  def update
    @bank_account.update_attributes(bank_account_params)

    if @bank_account.valid?
      flash[:notice] = 'Compte mis à jour avec succès'
      # redirect_to admin_user_path @bank_account.user
    else
      flash[:alert] = 'Une erreur est survenue'
    end
    redirect_to admin_user_path @bank_account.user
  end

  private

    def bank_account_params
      params.require(:bank_account).permit(:account_state_id)
    end

    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    def require_to_be_admin
      unless current_user.role.role_tid == Role::ADMIN_ROLE_TID
        render :file => "#{Rails.root}/public/401", :layout => false, :status => :unauthorized
      end
    end

end

app/controllers/client/bank_accounts_controller.rb
class Client::BankAccountsController < ApplicationController


  before_action :authenticate_user!
  before_action :set_bank_account, only: [:show]
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found
  before_action :require_to_be_client

  def index
    @bank_accounts = BankAccount.where(user_id: current_user.id)
  end


  def new
    @bank_account = BankAccount.new
  end


  def create
    @bank_account = current_user.bank_accounts.create(bank_account_params.merge(user: current_user))

    if @bank_account.valid?
      flash[:notice] = 'Compte crée avec succès'
      redirect_to client_bank_accounts_path
    else
      render :new, status: :unprocessable_entity
    end
  end


  def show
    @transactions = @bank_account.transactions.order(created_at: :desc)
      .paginate(:page => params[:page], :per_page => 5)
  end


  private

    def bank_account_params
      params.require(:bank_account).permit(:branch_code, :sort_code, :account_number, :rib_key)
    end

    def set_bank_account
      @bank_account = BankAccount.find(params[:id])
    end

    def not_found(e)
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
    end

    def require_to_be_client
      unless current_user.role.role_tid == Role::CLIENT_ROLE_TID
        render :file => "#{Rails.root}/public/401", :layout => false, :status => :unauthorized
      end
    end


end

app/helpers/admin/bank_accounts_helper.rb
module Admin::BankAccountsHelper
end

app/helpers/client/bank_accounts_helper.rb
module Client::BankAccountsHelper
end

app/views/shared/bank_accounts/_bank_account_details.html.erb
<tbody>
  <tr>
    <td><%= account.branch_code %></td>
    <td><%= account.sort_code %></td>
    <td><%= account.account_number%></td>
    <td><%= account.rib_key %></td>
    <td><%= account.account_state.state %></td>
    <td><%= number_to_currency(account.balance, locale: "fr", precision: 2)  %></td>

    <% if current_user.role.role_tid == Role::ADMIN_ROLE_TID %>
      <td>
        <% if account.account_state.state_tid == AccountState::PENDING_ACTIVATION_STATE_TID %>
          <%= button_to admin_bank_account_path(account), method: :put, class: 'btn btn-primary btn-sm' do %>
            <span><%= t('.activated_bank_account_btn') %></span>
            <%= hidden_field_tag "bank_account[account_state_id]", AccountState::ACTIVE_STATE_TID %>
          <% end %>
        <% elsif account.account_state.state_tid == AccountState::ACTIVE_STATE_TID %>
          <%= button_to admin_bank_account_path(account), method: :put, class: 'btn btn-danger btn-sm' do %>
            <span><%= t('.close_bank_account_btn') %></span>
            <%= hidden_field_tag "bank_account[account_state_id]", AccountState::CLOSED_STATE_TID %>
          <% end %>
        <% end %>
      </td>
    <% elsif current_user.role.role_tid == Role::CLIENT_ROLE_TID %>
      <td>
        <%= link_to client_bank_account_path(account) do %>
          <%= image_tag 'glyphicons-52-eye-open', class: 'img-responsive' %>
        <% end %>
        <%= link_to'#', onclick: "printRIB('#{account.branch_code}', '#{account.sort_code}',
          '#{account.account_number}', '#{account.rib_key}', '#{account.user.title}',
          '#{account.user.firstname}', '#{account.user.lastname}', '#{account.user.city}')" do %>
          <%= image_tag 'glyphicons-16-print', class: 'img-responsive' %>
        <% end %>
      </td>
    <% end %>
  </tr>
</tbody>

<script type="text/javascript">

  function printRIB(branchCode, sortCode, accountNumber, ribKey, userTitle,
    userFirstname, userLastname, userCity)
  {
    var win = window.open();
    self.focus();
    win.document.open();
    win.document.write('<'+'html'+'><'+'body'+'>');
    win.document.write('<'+'table border=\"1\"'+'><'+'tr'+'>');
    win.document.write('<'+'thead'+'><'+'tr'+'>');
    win.document.write('<'+'th'+'>');
    win.document.write('Code Banque');
    win.document.write('<'+'/th'+'>');
    win.document.write('<'+'th'+'>');
    win.document.write('Code Guichet');
    win.document.write('<'+'/th'+'>');
    win.document.write('<'+'th'+'>');
    win.document.write('Numéro de compte');
    win.document.write('<'+'/th'+'>');
    win.document.write('<'+'th'+'>');
    win.document.write('clé RIB');
    win.document.write('<'+'/th'+'>');
    win.document.write('<'+'/tr'+'><'+'/thead'+'>');
    win.document.write('<'+'td'+'>');
    win.document.write(branchCode);
    win.document.write('<'+'/td'+'>');
    win.document.write('<'+'td'+'>');
    win.document.write(sortCode);
    win.document.write('<'+'/td'+'>');
    win.document.write('<'+'td'+'>');
    win.document.write(accountNumber);
    win.document.write('<'+'/td'+'>');
    win.document.write('<'+'td'+'>');
    win.document.write(ribKey);
    win.document.write('<'+'/td'+'>');
    win.document.write('<'+'/tr'+'><'+'/table'+'>');
    win.document.write('<'+'p'+'>');
    win.document.write('Titulaire : ');
    win.document.write(userTitle);
    win.document.write(' ');
    win.document.write(userFirstname);
    win.document.write(' ');
    win.document.write(userLastname);
    win.document.write(', ');
    win.document.write(userCity);
    win.document.write('<'+'/p'+'>');
    win.document.write('<'+'/body'+'><'+'/html'+'>');
    win.document.close();
    win.print();
  }

</script>