config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: "customised_registrations" }
  root 'welcome#index'

  namespace :client do
    resources :bank_accounts, only: [:index, :new, :create, :show]
  end

  namespace :admin do
    resources :transactions, only: [:index, :new, :create, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bank_accounts, only: [:update]
  end

end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController


  before_action :authenticate_user!
  before_action :require_to_be_admin
  before_action :set_transaction, only: [:update]


  def index
    @transactions = Transaction.all.order(created_at: :desc)
      .paginate(:page => params[:page], :per_page => 5)
  end


  def new
    @transaction = Transaction.new
  end


  def create
    begin
      bank_account = BankAccount.find(params[:transaction][:bank_account_id])
      @transaction = bank_account.transactions.create(transaction_params)
      if @transaction.valid?
        TransactionManager.new(@transaction).execute_transaction
        flash[:notice] = 'Transaction crée avec succès'
        redirect_to admin_transactions_path
      else
        render :new, status: :unprocessable_entity
      end
    rescue BankAccountError => e
      flash[:alert] = e.message
      @transaction.destroy
      render :new
    end
  end


  def update
    begin
      @transaction.update_attributes(transaction_params)
      if @transaction.valid?
        TransactionManager.new(@transaction).execute_transaction
        flash[:notice] = 'Transaction mise à jour avec succès'
      else
        flash[:alert] = 'Une erreur est survenue'
      end
    rescue BankAccountError => e
      flash[:alert] = e.message
      @transaction.update_attributes(state_tid: TransactionState::PENDING_STATE_TID)
    end
    redirect_to admin_transactions_path
  end


  private

    def transaction_params
      params.require(:transaction).permit(:transaction_type, :state_tid, :bank_account_id, :value)
    end

    def require_to_be_admin
      unless current_user.role.role_tid == Role::ADMIN_ROLE_TID
        render :file => "#{Rails.root}/public/401", :layout => false, :status => :unauthorized
      end
    end

    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/views/admin/transactions/index.html.erb
<br/>
<button type="button" class="btn btn-primary btn-sm">
  <%= t('.pending_transaction_count') %>
  <span class="badge badge-light">
    <%= @transactions.where(transaction_state: TransactionState::PENDING_STATE_TID).count %>
  </span>
</button>
<br/><br/><br/>

<h3 class="text-center"><%= t('.transaction_list_page_title') %></h3>
<br/>

<div class="table-responsive-sm">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= t('.transaction_type_col_head') %></th>
        <th scope="col"><%= t('.transaction_state_col_head') %></th>
        <th scope="col"><%= t('.transaction_created_at_col_head') %></th>
        <th scope="col"><%= t('.transaction_value_col_head') %></th>
        <th scope="col"><%= t('.transaction_client_col_head') %></th>
        <th scope="col"><%= t('.transaction_bank_account_number_col_head') %></th>
        <th scope="col"><%= t('.transaction_actions_col_head') %></th>
      </tr>
    </thead>
    <% @transactions.each do |transaction| %>
      <tbody>
        <tr>
          <td><%= transaction.transaction_type %></td>
          <td><%= transaction.transaction_state.state %></td>
          <td><%= DateTime.parse(transaction.created_at.to_s).strftime('%A %B %d %H:%M') %></td>
          <td>
            <%= render partial: '/shared/transactions/transaction_value', locals: { transaction: transaction } %>
          </td>
          <td><%= transaction.bank_account.user.firstname %> <%= transaction.bank_account.user.lastname %></td>
          <td><%= transaction.bank_account.account_number %></td>
          <td>
            <% if transaction.transaction_state.state_tid == TransactionState::PENDING_STATE_TID %>
              <div class="btn-group btn-group-sm" role="group">
                <%= button_to admin_transaction_path(transaction), method: :put, class: 'btn btn-sm' do %>
                  <%= image_tag 'glyphicons-194-ok-sign', class: 'img-responsive' %>
                  <%= hidden_field_tag "transaction[state_tid]", TransactionState::VALIDATED_STATE_TID %>
                <% end %>
                <%= button_to admin_transaction_path(transaction), method: :put, class: 'btn btn-sm' do %>
                  <%= image_tag 'glyphicons-193-remove-sign', class: 'img-responsive' %>
                  <%= hidden_field_tag "transaction[state_tid]", TransactionState::CANCELLED_STATE_TID %>
                <% end %>
              </div>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

<%= will_paginate(@transactions, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>

app/views/admin/transactions/new.html.erb
<br/>
<h5><%= t('.transaction_form_head_page') %></h5>
<br/>
<%= simple_form_for @transaction, url: admin_transactions_path do |f| %>

  <%= f.radio_button :transaction_type, Transaction::CREDIT_TRANSACTION_TYPE, checked: true %>
  <%= f.label :transaction_type, t('.credit_radio_btn_label'), class: "form-check-label" %>

  <%= f.radio_button :transaction_type, Transaction::DEBIT_TRANSACTION_TYPE %>
  <%= f.label :transaction_type, t('.debit_radio_btn_label'), class: "form-check-label" %>

  <br/><br/>

  <%= f.label :state_tid, t('.state_select_label'), class: "form-check-label" %>
  <%= f.collection_select :state_tid,
    TransactionState.all.reject { |state| state.state_tid == TransactionState::CANCELLED_STATE_TID },
    :id, :state
  %>
  <br/>

  <%= f.label :value, t('.value_label'), class: "form-check-label" %>
  <%= f.input :value, label: false, placeholder: "0,0", input_html: { class: 'form-control', value: "" } %>
  <br/>

  <%= f.label :bank_account_id, t('.bank_account_label'), class: "form-check-label" %>
  <%= f.collection_select :bank_account_id, BankAccount.all, :id, :account_number %>

  <br/>
  <%= f.submit t('.create_btn'), class: 'btn btn-primary' %>

<% end %>

<script type="text/javascript">

  $("select").addClass("form-control");


  $('#new_transaction').validate({

    highlight: function(element) {
      jQuery(element).closest('.form-control').addClass('is-invalid');
    },
    unhighlight: function(element) {
      jQuery(element).closest('.form-control').removeClass('is-invalid');
    },
    errorElement: 'div',
    errorClass: 'invalid-feedback',

    rules: {
      'transaction[value]': { required: true, number: true }
    },
    messages: {
      'transaction[value]': {
        required: "Saisissez le montant de la transaction",
        number: "Le montant ne peut contenir que des chiffres"
      }
    }
  });

</script>