config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: "customised_registrations" }
  root 'welcome#index'

  namespace :client do
    resources :bank_accounts, only: [:index, :new, :create, :show]
  end

  namespace :admin do
    resources :transactions, only: [:index, :new, :create, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bank_accounts, only: [:update]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  validates :title, presence: true, inclusion: { in: %w(Mr Mme Mlle) }
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :birthday, presence: true
  validates :city, presence: true

  belongs_to :monthly_salary_range, foreign_key: "monthly_salary_range_id"
  belongs_to :role, foreign_key: "role_tid"
  has_many :bank_accounts, :dependent => :destroy

  after_create :setup_country
  after_create :setup_role


  private

    def setup_country
      self.update_attributes(country: "FR")
    end

    def setup_role
      self.update_attributes(role_tid: Role::CLIENT_ROLE_TID)
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController


  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_to_be_admin
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  def index
    @users = User.where(role_tid: Role::CLIENT_ROLE_TID)
  end

  def show
    @bank_accounts = @user.bank_accounts
  end

  def edit
  end

  def update
    @user.update_attributes(user_params)

    if @user.valid?
      flash[:notice] = 'Client mis à jour avec succès'
      redirect_to admin_users_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = 'Client supprimé avec succès'
    redirect_to admin_users_path
  end

  private

    def user_params
      params.require(:user).permit(:title, :firstname, :lastname, :birthday,
        :email, :city, :monthly_salary_range_id)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_to_be_admin
      unless current_user.role.role_tid == Role::ADMIN_ROLE_TID
        render :file => "#{Rails.root}/public/401", :layout => false, :status => :unauthorized
      end
    end

    def not_found(e)
      render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found
    end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<br/>
<h5><%= t('.user_edit_form_head_page') %> <%= @user.title %> <%= @user.firstname %> <%= @user.lastname %></h5>
<br/>
<%= simple_form_for @user, url: admin_user_path(@user) do |f| %>
  <%= render partial: '/shared/users/form', locals: { f: f } %>
  <%= f.submit t('.modify_btn'), class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/index.html.erb
<br/>
<button type="button" class="btn btn-primary btn-sm">
  <%= t('.client_count') %> <span class="badge badge-light"><%= @users.count %></span>
</button>

<br/><br/><br/>
<h3 class="text-center"><%= t('.user_list_page_title') %></h3>
<br/>
<div class="table-responsive-sm">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= t('.user_title_col_head') %></th>
        <th scope="col"><%= t('.user_firstname_col_head') %></th>
        <th scope="col"><%= t('.user_lastname_col_head') %></th>
        <th scope="col"><%= t('.user_birthday_col_head') %></th>
        <th scope="col"><%= t('.user_email_col_head') %></th>
        <th scope="col"><%= t('.user_city_col_head') %></th>
        <th scope="col"><%= t('.user_monthly_salary_range_col_head') %></th>
        <th scope="col"><%= t('.user_actions_col_head') %></th>
      </tr>
    </thead>
    <% @users.each do |user| %>
    <tbody>
      <tr>
        <td><%= user.title %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.birthday %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= user.monthly_salary_range.range %></td>
        <td>
          <div class="btn-group btn-group-sm" role="group" aria-label="...">
            <%= link_to admin_user_path(user), class: 'img-responsive' do %>
              <%= image_tag 'glyphicons-52-eye-open', class: 'img-responsive' %>
            <% end %>
            <%= link_to edit_admin_user_path(user), class: 'img-responsive' do %>
              <%= image_tag 'glyphicons-151-edit', class: 'img-responsive' %>
            <% end %>
            <%= link_to admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } do %>
              <%= image_tag 'glyphicons-208-remove', class: 'img-responsive' %>
            <% end %>
          </div>
        </td>
    <% end %>
  </table>
</div>

app/views/admin/users/show.html.erb
<br/>
<button type="button" class="btn btn-primary btn-sm">
  <%= t('.bank_account_count') %>
  <span class="badge badge-light">
    <%= @user.bank_accounts.count %>
  </span>
</button>
<br/><br/><br/>

<h3 class="text-center">
  <%= t('.bank_account_page_title') %> <%= @user.title %> <%= @user.firstname %> <%= @user.lastname %>
</h3>
<br/>

<div class="table-responsive-sm">
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= t('.bank_account_branch_code_col_head') %></th>
        <th scope="col"><%= t('.bank_account_sort_code_col_head') %></th>
        <th scope="col"><%= t('.bank_account_number_col_head') %></th>
        <th scope="col"><%= t('.bank_account_rib_key_col_head') %></th>
        <th scope="col"><%= t('.bank_account_state_col_head') %></th>
        <th scope="col"><%= t('.bank_account_balance_col_head') %></th>
        <th scope="col"><%= t('.bank_account_actions_col_head') %></th>
      </tr>
    </thead>
    <% @bank_accounts.each do |account| %>
      <%= render partial: '/shared/bank_accounts/bank_account_details', locals: { account: account} %>
    <% end %>
  </table>
</div>