config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { registrations: "customised_registrations" }
  root 'welcome#index'

  namespace :client do
    resources :bank_accounts, only: [:index, :new, :create, :show]
  end

  namespace :admin do
    resources :transactions, only: [:index, :new, :create, :update]
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :bank_accounts, only: [:update]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CreditApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="<%= root_path %>">CREDIT APP</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!-- <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li> -->
        </ul>

        <% if user_signed_in? %>
          <% if current_user.role.role_tid == Role::CLIENT_ROLE_TID %>
            <%= link_to t('.my_bank_accounts'), client_bank_accounts_path, class: 'nav-link' %>
            <%= link_to t('.new_bank_account'), new_client_bank_account_path, class: 'nav-link' %>
          <% elsif current_user.role.role_tid == Role::ADMIN_ROLE_TID %>
            <%= link_to t('.show_transactions'), admin_transactions_path, class: 'nav-link' %>
            <%= link_to t('.new_transaction'), new_admin_transaction_path, class: 'nav-link' %>
            <%= link_to t('.manager_clients'), admin_users_path, class: 'nav-link' %>
          <% end %>
          <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <%= link_to t('.sign_in'), new_user_session_path, class: 'nav-link' %>
          <%= link_to t('.sign_up'), new_user_registration_path, class: 'nav-link' %>
        <% end %>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-sm">

          <% if notice.present? %>
            <p class="text-success"><%= notice %></p>
          <% end %>

        	<% if alert.present? %>
            <p class="text-danger"><%= alert %></p>
        	<% end %>

          <%= yield %>

        </div>
      </div>
    </div>

  </body>

</html>